// <auto-generated />
using System;
using HealthDataGateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealthDataGateway.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116095712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealthDataGateway.Data.Models.Acknowledgement", b =>
                {
                    b.Property<int>("AcknowledgementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcknowledgementId"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IncomingRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("RespondedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("AcknowledgementId");

                    b.HasIndex("IncomingRequestId");

                    b.ToTable("Acknowledgements");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.ActivityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("PerformedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LogId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.ConnectorRequest", b =>
                {
                    b.Property<int>("ConnectorRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConnectorRequestId"));

                    b.Property<string>("AuthType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("OAuth2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<byte[]>("EncryptedPayload")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EncryptionType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("AES-256");

                    b.Property<bool>("IsFHIRCompliant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TransferRequestId")
                        .HasColumnType("int");

                    b.HasKey("ConnectorRequestId");

                    b.HasIndex("Status");

                    b.HasIndex("TransferRequestId");

                    b.ToTable("ConnectorRequests");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<DateTime>("DiagnosedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("DiagnosisText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("PatientId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HospitalId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("HospitalId");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            HospitalId = 1,
                            CreatedAt = new DateTime(2026, 1, 16, 15, 27, 12, 56, DateTimeKind.Local).AddTicks(5925),
                            HospitalName = "City General Hospital",
                            IsActive = true
                        },
                        new
                        {
                            HospitalId = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 15, 27, 12, 56, DateTimeKind.Local).AddTicks(5944),
                            HospitalName = "St. Mary's Medical Center",
                            IsActive = true
                        },
                        new
                        {
                            HospitalId = 3,
                            CreatedAt = new DateTime(2026, 1, 16, 15, 27, 12, 56, DateTimeKind.Local).AddTicks(5947),
                            HospitalName = "Regional Trauma Center",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.IncomingTransferRequest", b =>
                {
                    b.Property<int>("IncomingRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomingRequestId"));

                    b.Property<int>("ConnectorRequestId")
                        .HasColumnType("int");

                    b.Property<string>("IncomingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("SourceHospitalId")
                        .HasColumnType("int");

                    b.Property<int>("TargetHospitalId")
                        .HasColumnType("int");

                    b.HasKey("IncomingRequestId");

                    b.HasIndex("ConnectorRequestId");

                    b.HasIndex("IncomingStatus");

                    b.HasIndex("SourceHospitalId");

                    b.HasIndex("TargetHospitalId");

                    b.ToTable("IncomingTransferRequests");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("LocalPatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PatientId");

                    b.HasIndex("HospitalId", "LocalPatientId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.TransferRequest", b =>
                {
                    b.Property<int>("TransferRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferRequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SourceHospitalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TargetHospitalId")
                        .HasColumnType("int");

                    b.HasKey("TransferRequestId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SourceHospitalId");

                    b.HasIndex("Status");

                    b.HasIndex("TargetHospitalId");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Acknowledgement", b =>
                {
                    b.HasOne("HealthDataGateway.Data.Models.IncomingTransferRequest", "IncomingTransferRequest")
                        .WithMany("Acknowledgements")
                        .HasForeignKey("IncomingRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomingTransferRequest");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.ConnectorRequest", b =>
                {
                    b.HasOne("HealthDataGateway.Data.Models.TransferRequest", "TransferRequest")
                        .WithMany("ConnectorRequests")
                        .HasForeignKey("TransferRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransferRequest");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Diagnosis", b =>
                {
                    b.HasOne("HealthDataGateway.Data.Models.Patient", "Patient")
                        .WithMany("Diagnoses")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.IncomingTransferRequest", b =>
                {
                    b.HasOne("HealthDataGateway.Data.Models.ConnectorRequest", "ConnectorRequest")
                        .WithMany("IncomingTransferRequests")
                        .HasForeignKey("ConnectorRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthDataGateway.Data.Models.Hospital", "SourceHospital")
                        .WithMany()
                        .HasForeignKey("SourceHospitalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthDataGateway.Data.Models.Hospital", "TargetHospital")
                        .WithMany()
                        .HasForeignKey("TargetHospitalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ConnectorRequest");

                    b.Navigation("SourceHospital");

                    b.Navigation("TargetHospital");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Patient", b =>
                {
                    b.HasOne("HealthDataGateway.Data.Models.Hospital", "Hospital")
                        .WithMany("Patients")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.TransferRequest", b =>
                {
                    b.HasOne("HealthDataGateway.Data.Models.Patient", "Patient")
                        .WithMany("TransferRequests")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthDataGateway.Data.Models.Hospital", "SourceHospital")
                        .WithMany("SourceTransferRequests")
                        .HasForeignKey("SourceHospitalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealthDataGateway.Data.Models.Hospital", "TargetHospital")
                        .WithMany("TargetTransferRequests")
                        .HasForeignKey("TargetHospitalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SourceHospital");

                    b.Navigation("TargetHospital");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.ConnectorRequest", b =>
                {
                    b.Navigation("IncomingTransferRequests");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Hospital", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("SourceTransferRequests");

                    b.Navigation("TargetTransferRequests");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.IncomingTransferRequest", b =>
                {
                    b.Navigation("Acknowledgements");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.Patient", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("TransferRequests");
                });

            modelBuilder.Entity("HealthDataGateway.Data.Models.TransferRequest", b =>
                {
                    b.Navigation("ConnectorRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
